development:
  sessions:
    default:
      database: orgwerks_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: orgwerks_testing
      hosts:
        - localhost:27017
